school_1/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views
urlpatterns = [
    url('^login/$', views.login, name='login'),
    url('^logcheck/$', views.log_check, name='logcheck'),
    url('^show/(?P<patient_id>[0-9]+)$',
        views.show_patient, name='show_patient'),
    url('^edit_patient/(?P<patient_id>[0-9]+)$',
        views.edit_patient, name='edit_patient'),
    url('^edit/action$', views.edit_action, name='edit_action'),
    url('^search/$', views.search_patient, name='search_patient'),
    url('^back_index/$', views.back_index, name='back_index')
]


# 设置静态文件路径
urlpatterns += staticfiles_urlpatterns()

school_hos/school_1/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views
urlpatterns = [
    url('^login/$', views.login, name='login'),
    url('^logcheck/$', views.log_check, name='logcheck'),
    url('^show/(?P<patient_id>[0-9]+)$',
        views.show_patient, name='show_patient'),
    url('^edit_patient/(?P<patient_id>[0-9]+)$',
        views.edit_patient, name='edit_patient'),
    url('^edit/action$', views.edit_action, name='edit_action'),
    url('^search/$', views.search_patient, name='search_patient'),
    url('^back_index/$', views.back_index, name='back_index')
]


# 设置静态文件路径
urlpatterns += staticfiles_urlpatterns()

school_hos/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles
from django.contrib import admin
from django.urls import path, include
from django.views import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('school_1/', include(('school_1.urls', 'school_1'), namespace='school_1')),
    url('^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static')
]

# 设置静态文件路径
urlpatterns += staticfiles_urlpatterns()

school_1/models.py
from django.db import models

# Create your models here.


class Patient(models.Model):
    pname = models.CharField(max_length=32, default='姓名')
    pid = models.CharField(max_length=64, null=True)
    pheat = models.FloatField(null=False, default=37.0)
    pgender = models.CharField(max_length=5, default='男', null=False)
    psymptom1 = models.TextField(null=True)
    psymptom2 = models.TextField(null=True)
    psymptom3 = models.TextField(null=True)
    ptime = models.DateTimeField(null=True)

    def __str__(self):
        return self.pname

school_hos/school_1/models.py
from django.db import models

# Create your models here.


class Patient(models.Model):
    pname = models.CharField(max_length=32, default='姓名')
    pid = models.CharField(max_length=64, null=True)
    pheat = models.FloatField(null=False, default=37.0)
    pgender = models.CharField(max_length=5, default='男', null=False)
    psymptom1 = models.TextField(null=True)
    psymptom2 = models.TextField(null=True)
    psymptom3 = models.TextField(null=True)
    ptime = models.DateTimeField(null=True)

    def __str__(self):
        return self.pname

school_1/views.py
from django.shortcuts import render
from django.contrib import messages
from . import models
import datetime
from django.http import HttpResponse
# Create your views here.


def login(request):
    return render(request, 'school_1/login.html')


def log_check(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    patients = models.Patient.objects.all()
    if (str(username) == 'yiwushi' and str(password) == '123456'):
        return render(request, 'school_1/index.html', {'patients': patients})
    messages.success(request, "用户名或密码错误")


def show_patient(request, patient_id):
    patient = models.Patient.objects.get(pk=patient_id)
    return render(request, 'school_1/show_page.html', {'patient': patient})


def edit_patient(request, patient_id):
    if str(patient_id) == '0':
        time_now = datetime.datetime.now()
        return render(request, 'school_1/edit_patient.html', {'time': time_now})
    patient = models.Patient.objects.get(pk=patient_id)
    return render(request, 'school_1/edit_patient.html', {'patient': patient})


def edit_action(request):
    patient_name = request.POST.get('firstname', '姓名')
    patient_idnumber = request.POST.get('idnumber')
    patient_heat = request.POST.get('heat')
    patient_symptom1 = request.POST.get('symptom_1')
    patient_symptom2 = request.POST.get('symptom_2')
    patient_symptom3 = request.POST.get('symptom_3')
    patient_time = datetime.datetime.now()
    patient_gender_1 = request.POST.get('inlineRadioOptions', '男')
    patient_gender = str(patient_gender_1)
    patient_did = request.POST.get('patient_id')
    if str(patient_did) == '0':
        models.Patient.objects.create(pname=patient_name, pid=patient_idnumber, pheat=patient_heat,
                                      pgender=patient_gender, psymptom1=patient_symptom1, psymptom2=patient_symptom2, psymptom3=patient_symptom3,
                                      ptime=patient_time)
        patients = models.Patient.objects.all()
        return render(request, 'school_1/index.html', {'patients': patients})
    patient = models.Patient.objects.get(pk=patient_did)
    patient.pname = patient_name
    patient.pid = patient_idnumber
    patient.pheat = patient_heat
    patient.pgender = patient_gender
    patient.psymptom1 = patient_symptom1
    patient.psymptom2 = patient_symptom2
    patient.psymptom3 = patient_symptom3
    patient.save()
    return render(request, 'school_1/show_page.html', {'patient': patient})


def search_patient(request):
    nameid_1 = request.POST.get('name_id')
    nameid = str(nameid_1)
    if models.Patient.objects.filter(pid=nameid):
        patients = models.Patient.objects.filter(pid=nameid)
    elif models.Patient.objects.filter(pname=nameid):
        patients = models.Patient.objects.filter(pname=nameid)
    else:
        patients = models.Patient.objects.all()
    return render(request, 'school_1/index.html', {'patients': patients})

    # try:
    #   models.Patient.objects.filter(pid=nameid)
    #  patients = models.Patient.objects.filter(pid=nameid)
    # except models.Patient.DoesNotExist:
    #   try:
    #      models.Patient.objects.filter(pname=nameid)
    #     patients = models.Patient.objects.filter(pname=nameid)
    # except models.Patient.DoesNotExist:
    #   patients = models.Patient.objects.all()
    # return render(request, 'school_1/index.html', {'patients': patients})


def back_index(request):
    patients = models.Patient.objects.all()
    return render(request, 'school_1/index.html', {'patients': patients})

school_hos/school_1/views.py
from django.shortcuts import render
from django.contrib import messages
from . import models
import datetime
from django.http import HttpResponse
# Create your views here.


def login(request):
    return render(request, 'school_1/login.html')


def log_check(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    patients = models.Patient.objects.all()
    if (str(username) == 'yiwushi' and str(password) == '123456'):
        return render(request, 'school_1/index.html', {'patients': patients})
    messages.success(request, "用户名或密码错误")


def show_patient(request, patient_id):
    patient = models.Patient.objects.get(pk=patient_id)
    return render(request, 'school_1/show_page.html', {'patient': patient})


def edit_patient(request, patient_id):
    if str(patient_id) == '0':
        time_now = datetime.datetime.now()
        return render(request, 'school_1/edit_patient.html', {'time': time_now})
    patient = models.Patient.objects.get(pk=patient_id)
    return render(request, 'school_1/edit_patient.html', {'patient': patient})


def edit_action(request):
    patient_name = request.POST.get('firstname', '姓名')
    patient_idnumber = request.POST.get('idnumber')
    patient_heat = request.POST.get('heat')
    patient_symptom1 = request.POST.get('symptom_1')
    patient_symptom2 = request.POST.get('symptom_2')
    patient_symptom3 = request.POST.get('symptom_3')
    patient_time = datetime.datetime.now()
    patient_gender_1 = request.POST.get('inlineRadioOptions', '男')
    patient_gender = str(patient_gender_1)
    patient_did = request.POST.get('patient_id')
    if str(patient_did) == '0':
        models.Patient.objects.create(pname=patient_name, pid=patient_idnumber, pheat=patient_heat,
                                      pgender=patient_gender, psymptom1=patient_symptom1, psymptom2=patient_symptom2, psymptom3=patient_symptom3,
                                      ptime=patient_time)
        patients = models.Patient.objects.all()
        return render(request, 'school_1/index.html', {'patients': patients})
    patient = models.Patient.objects.get(pk=patient_did)
    patient.pname = patient_name
    patient.pid = patient_idnumber
    patient.pheat = patient_heat
    patient.pgender = patient_gender
    patient.psymptom1 = patient_symptom1
    patient.psymptom2 = patient_symptom2
    patient.psymptom3 = patient_symptom3
    patient.save()
    return render(request, 'school_1/show_page.html', {'patient': patient})


def search_patient(request):
    nameid_1 = request.POST.get('name_id')
    nameid = str(nameid_1)
    if models.Patient.objects.filter(pid=nameid):
        patients = models.Patient.objects.filter(pid=nameid)
    elif models.Patient.objects.filter(pname=nameid):
        patients = models.Patient.objects.filter(pname=nameid)
    else:
        patients = models.Patient.objects.all()
    return render(request, 'school_1/index.html', {'patients': patients})

    # try:
    #   models.Patient.objects.filter(pid=nameid)
    #  patients = models.Patient.objects.filter(pid=nameid)
    # except models.Patient.DoesNotExist:
    #   try:
    #      models.Patient.objects.filter(pname=nameid)
    #     patients = models.Patient.objects.filter(pname=nameid)
    # except models.Patient.DoesNotExist:
    #   patients = models.Patient.objects.all()
    # return render(request, 'school_1/index.html', {'patients': patients})


def back_index(request):
    patients = models.Patient.objects.all()
    return render(request, 'school_1/index.html', {'patients': patients})

school_hos/school_1/templates/school_1/edit_patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>数据可视化demo</title>
    <link href="/static/css/common.css" rel="stylesheet">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-table.css" rel="stylesheet">
    <link href="/static/css/pagination.css" rel="stylesheet">
    <script src="/static/js/Plugin/jquery-3.3.1.min.js"></script>
    <script src="/static/js/Plugin/echarts.min.js"></script>
    <script src="/static/js/Plugin/jquery.pagination.min.js"></script>
    <script src="/static/js/common.js"></script>
    <script src="static/js/chronic.js"></script>
</head>
<body>
<!--顶部-->
<header class="header left">
    <div class="left nav">
        <ul>
            
          </ul>
    </div>
    <div class="header_center left" style="position:relative">
        <h2><strong>大数据展示</strong></h2>

    </div>
    <div class="right nav text_right">
        <ul>

        </ul>
    </div>

</header>
<!--内容部分-->
<div class="con left" style="width: 98%;margin-left: 1%;margin-bottom: 25px;height: 100%;">


    <div class="div_any_child" style="height: 100%;">
          <div class="table_p" style="height: 96%;margin-top: 20px;">
            <form class="form-horizontal" role="form" method="POST" action="{% url 'school_1:edit_action' %}">
              {% csrf_token %}
              {% if patient %}
              <input type="hidden" name="patient_id" class="form-control" id="firstname" value="{{patient.id}}">

                <div class="form-group">
                  <label for="firstname" class="col-sm-2 control-label" style="color:#fff">名字</label>
                  <div class="col-sm-2">
                    <input type="text" name="firstname" class="form-control" id="firstname" value="{{patient.pname}}">

                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-11">
                    <label class="radio-inline" style="color:#fff">男 &nbsp;&nbsp;&nbsp;&nbsp;
                      <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="男"> 
                    </label>
                    <label class="radio-inline" style="color:#fff">女 &nbsp;&nbsp;&nbsp;&nbsp;
                      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="女"> 
                    </label>
                  </div>
                </div>
               

                <div class="form-group">
                  <label for="heat" class="col-sm-2 control-label" style="color:#fff">体温</label>
                  <div class="col-sm-2">
                    <input type="text" class="form-control" id="heat" name="heat" value="{{patient.pheat}}">
                  </div>
                </div>


                <div class="form-group">
                    <label for="idnumber" class="col-sm-2 control-label" style="color:#fff">身份证号码</label>
                    <div class="col-sm-6">
                      <input type="text" class="form-control" id="idnumber" name="idnumber" value="{{patient.pid}}">
                    </div>
                </div>

                <div class="form-group">
                  <label for="symptom_1" class="col-sm-2 control-label" style="color:#fff">主要症状1</label>
                  <div class="col-sm-6">
                    <textarea  class="form-control" id="symptom_1" name="symptom_1" cols="30" rows="30" style="height: 150px; width: 30ß0px;">{{patient.psymptom1}}</textarea>
                  </div>
              </div>

              <div class="form-group">
                <label for="symptom_2" class="col-sm-2 control-label" style="color:#fff">主要症状2</label>
                <div class="col-sm-6">
                  <textarea  class="form-control" id="symptom_2" name="symptom_2" cols="30" rows="30" style="height: 150px; width: 30ß0px;">{{patient.psymptom2}}</textarea>
                </div>
            </div>

            <div class="form-group">
              <label for="symptom_3" class="col-sm-2 control-label" style="color:#fff">主要症状3</label>
              <div class="col-sm-6">
                <textarea  class="form-control" id="symptom_3" name="symptom_3" cols="30" rows="30" style="height: 150px; width: 30ß0px;">{{patient.psymptom3}}</textarea>
              </div>
          </div>

          <div class="form-group">
            <label for="patient_date" class="col-sm-2 control-label" style="color:#fff">日期</label>
            <div class="col-sm-2">
              <input type="text" class="form-control" id="patient_date" name="patient_date" value="{{patient.ptime}}">
            </div>
          </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-default" style="margin-left:20px"><input type="submit" name="symptom_submit" value="提交" style="background:none;  
                      outline:none;  border:none;"></button>
                  </div>
                </div>



                {% else %}
                <input type="hidden" name="patient_id" class="form-control" id="firstname" value="0">

                <div class="form-group">
                  <label for="firstname" class="col-sm-2 control-label" style="color:#fff">名字</label>
                  <div class="col-sm-2">
                    <input type="text" name="firstname" class="form-control" id="firstname" >

                  </div>
                </div>
               
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-11">
                    <label class="radio-inline" style="color:#fff">男 &nbsp;&nbsp;&nbsp;&nbsp;
                      <input type="radio" name="inlineRadioOptions" id="inlineRadio1"  > 
                    </label>
                    <label class="radio-inline" style="color:#fff">女 &nbsp;&nbsp;&nbsp;&nbsp;
                      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" > 
                    </label>
                  </div>
                </div>
                

                <div class="form-group">
                  <label for="heat" class="col-sm-2 control-label" style="color:#fff">体温</label>
                  <div class="col-sm-2">
                    <input type="text" class="form-control" id="heat" name="heat" >
                  </div>
                </div>


                <div class="form-group">
                    <label for="idnumber" class="col-sm-2 control-label" style="color:#fff">身份证号码</label>
                    <div class="col-sm-6">
                      <input type="text" class="form-control" id="idnumber" name="idnumber" >
                    </div>
                </div>

                <div class="form-group">
                  <label for="symptom_1" class="col-sm-2 control-label" style="color:#fff">主要症状1</label>
                  <div class="col-sm-6">
                    <textarea  class="form-control" id="symptom_1" name="symptom_1" cols="30" rows="30" style="height: 150px; width: 30ß0px;"></textarea>
                  </div>
              </div>

              <div class="form-group">
                <label for="symptom_2" class="col-sm-2 control-label" style="color:#fff">主要症状2</label>
                <div class="col-sm-6">
                  <textarea  class="form-control" id="symptom_2" name="symptom_2" cols="30" rows="30" style="height: 150px; width: 30ß0px;"></textarea>
                </div>
            </div>

            <div class="form-group">
              <label for="symptom_3" class="col-sm-2 control-label" style="color:#fff">主要症状3</label>
              <div class="col-sm-6">
                <textarea  class="form-control" id="symptom_3" name="symptom_3" cols="30" rows="30" style="height: 150px; width: 30ß0px;"></textarea>
              </div>
          </div>

          <div class="form-group">
            <label for="patient_date" class="col-sm-2 control-label" style="color:#fff">日期</label>
            <div class="col-sm-2">
              <input type="text" class="form-control" id="patient_date" name="patient_date" value="{{time}}">
            </div>
          </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-default" style="margin-left:20px"><input type="submit" name="symptom_submit" value="提交" style="background:none;  
                      outline:none;  border:none;"></button>
                  </div>
                </div>
                {% endif %}
              </form>

          </div>
          
        </div>


    </div>
</div>
</body>
</html>

school_hos/school_1/templates/school_1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>数据可视化demo</title>
    <link href="/static/css/common.css" rel="stylesheet">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-table.css" rel="stylesheet">
    <link href="/static/css/pagination.css" rel="stylesheet">
    <script src="/static/js/Plugin/jquery-3.3.1.min.js"></script>
    <script src="/static/js/Plugin/echarts.min.js"></script>
    <script src="/static/js/Plugin/jquery.pagination.min.js"></script>
    <script src="/static/js/common.js"></script>
    <script src="/static/js/chronic.js"></script>
</head>
<body>
<!--顶部-->
<header class="header left">
    <div class="left nav">
        <ul>
      
          </ul>
    </div>
    <div class="header_center left" style="position:relative">
        <h2><strong>大数据展示</strong></h2>

    </div>
    <div class="right nav text_right">
        <ul>

        </ul>
    </div>

</header>
<!--内容部分-->
<div class="con left" style="width: 98%;margin-left: 1%;margin-bottom: 25px;">
    <form method="POST" action="{% url 'school_1:search_patient' %}" style="display: inline-block;">
        {% csrf_token %} 
        <input type="text" placeholder="请输入身份证" name="name_id" style="width: 180px;height: 28px;border-radius: 3px;text-indent: 1em;border: 1px solid#4b8df8;" /><button class="btn btn-primary btn-sm" style="margin-left:20px">
        <span class="glyphicon glyphicon-search"></span>&nbsp;
            <input type="submit"  value="查找" style="background:none;  
            outline:none;  border:none;">
           </button>

            
</form>
<button class="btn btn-primary btn-sm" style="margin-left:20px"><span class="glyphicon glyphicon-plus"></span>&nbsp;<a href="{% url 'school_1:edit_patient' 0 %}" style="background:none;  
    outline:none;  border:none;color:#fff;">增添</a></button>
    
    <div class="div_any_child">
          <div class="table_p" style="height: 96%;margin-top: 20px;">
              <table>
                  <thead><tr>
                      <th>序列号</th>
                      <th>姓名</th>
                      <th>性别</th>
                      <th>身份证号</th>
                      <th>体温</th>
                      <th>操作</th>
                  </tr>
                  </thead>
                  <tbody>
                      {% for patient in patients%}
                  <tr><td>{{patient.id}}</td><td>{{patient.pname}}</td><td>{{patient.pgender}}</td><td>{{patient.pid}}</td><td>{{patient.pheat}}</td><td><button class="btn btn-primary btn-sm">
                      <a href="{% url 'school_1:show_patient' patient.id %}" style="text-decoration: none;color:#fff;">查看</a></button></td></tr>
                  
                    {% endfor %}  
                </tbody>

              </table>
          </div>
          <div class="box">
              <div id="pagination" class="page fl"></div>
          </div>
        </div>


    </div>
</div>
</body>
</html>

school_hos/school_1/templates/school_1/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>1-3</title>
		<style>
            body{
                background:url("/static/images/1.jpeg") no-repeat center top;
            }
            #table_1{
                border: 2px solid #000033;
            }
        </style>
       
		<script type="text/javascript" >
		     function check() {
			 var a=document.getElementById('username').value;
			 var b=document.getElementById('password').value;
			 var c=document.getElementById('Username').value;
			 var d=document.getElementById('Password').value;
			 if(a!=c)
			      alert("name error!");
			 else if(b!=d)
			      alert("password error!");
			 else alert("Welcome!");
		     }
        </script>
         <link rel="stylesheet" href="/static/css/login.css">
	</head>
	<body>
          
	      <div id="bg">
		   <form action="{% url 'school_1:logcheck' %}" method="POST">
               {% csrf_token%}
		      <table id="table_1" width="100%">
			 <tr>
				<td style="text-align:right" height:"100px">
				<p>用户名:</p></td>
				<td><input type="text" id="username" name="username">
				<input type="hidden" id="Username" value="yiwushi"></td>
			</tr>
			<tr>
				<td style="text-align:right">
				<p>密码:</p></td>
				<td><input type="password" id="password" name="password">
				<input type="hidden" id="Password" value="123456"></td>
			</tr>
			<tr>
				 <td>&nbsp;</td>
                  <td><input type="button" value="验证" onclick='check()'></td>
                  <td><input type="submit" value="登陆" ></td>

			</tr>
			</table>
		    </form>
        </div>
        
	</body>
</html>
	 

school_hos/school_1/templates/school_1/show_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>数据可视化demo</title>
    <link href="/static/css/common.css" rel="stylesheet">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-table.css" rel="stylesheet">
    <link href="/static/css/pagination.css" rel="stylesheet">
    <script src="/static/js/Plugin/jquery-3.3.1.min.js"></script>
    <script src="/static/js/Plugin/echarts.min.js"></script>
    <script src="/static/js/Plugin/jquery.pagination.min.js"></script>
    <script src="/static/js/common.js"></script>
    <script src="static/js/chronic.js"></script>
</head>
<body>
<!--顶部-->
<header class="header left">
    <div class="left nav">
        <ul>
            <li><i class="nav_1"></i><a href="{% url 'school_1:back_index' %}">首页</a> </li>
            
          </ul>
    </div>
    <div class="header_center left" style="position:relative">
        <h2><strong>大数据展示</strong></h2>

    </div>
    <div class="right nav text_right">
        <ul>

        </ul>
    </div>

</header>
<!--内容部分-->
<div class="con left" style="width: 98%;margin-left: 1%;margin-bottom: 25px;height: 100%;">


    <div class="div_any_child" style="height: 100%;">
          <div class="table_p" style="height: 96%;margin-top: 20px;">
              
            <form class="form-horizontal" role="form">
                <div class="form-group">
                  <label for="firstname" class="col-sm-2 control-label" style="color:#fff">名字</label>
                  <div class="col-sm-2">
                    <input type="text"  class="form-control" id="firstname" readonly='true' value="{{patient.pname}}">
                  </div>
                </div>
                {% if patient.pgender == "男" %}
 
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-11">
                    <div class="checkbox">
                      <label style="color:#fff">男
                        <input type="radio"  id="optionsRadios1" readonly='true' value="男" checked="checked">
                      </label>
                      <label style="color:#fff">女
                        <input type="radio" id="optionsRadios2" readonly='true'  value="女" disabled>
                      </label>
                    </div>
                  </div>
                </div>
                {% else %}
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-11">
                    <div class="checkbox">
                      <label style="color:#fff">男
                        <input type="radio"  id="optionsRadios1" readonly='true'  value="男" disabled>
                      </label>
                      <label style="color:#fff">女
                        <input type="radio" id="optionsRadios2" readonly='true'  value="女" checked="checked">
                      </label>
                    </div>
                  </div>
                </div>
                {% endif %}

                <div class="form-group">
                  <label for="heat" class="col-sm-2 control-label" style="color:#fff">体温</label>
                  <div class="col-sm-2">
                    <input type="text" class="form-control" id="heat" readonly='true' value="{{patient.pheat}}">
                  </div>
                </div>


                <div class="form-group">
                    <label for="idnumber" class="col-sm-2 control-label" style="color:#fff">身份证号码</label>
                    <div class="col-sm-6">
                      <input type="text" class="form-control" id="idnumber" readonly='true' value="{{patient.pid}}">
                    </div>
                </div>

                <div class="form-group">
                  <label for="symptom_1" class="col-sm-2 control-label" style="color:#fff">主要症状1</label>
                  <div class="col-sm-6">
                    <textarea  class="form-control" id="symptom_1" cols="30" rows="30" style="height: 150px; width: 30ß0px;" readonly='true' >{{patient.psymptom1}}</textarea>
                  </div>
              </div>

              <div class="form-group">
                <label for="symptom_2" class="col-sm-2 control-label" style="color:#fff">主要症状2</label>
                <div class="col-sm-6">
                  <textarea  class="form-control" id="symptom_2"  cols="30" rows="30" style="height: 150px; width: 30ß0px;" readonly='true'>{{patient.psymptom2}}</textarea>
                </div>
            </div>

            <div class="form-group">
              <label for="symptom_3" class="col-sm-2 control-label" style="color:#fff">主要症状3</label>
              <div class="col-sm-6">
                <textarea  class="form-control" id="symptom_3"  cols="30" rows="30" style="height: 150px; width: 30ß0px;" readonly='true'>{{patient.psymptom3}}</textarea>
              </div>
          </div>

          <div class="form-group">
            <label for="patient_date" class="col-sm-2 control-label" style="color:#fff">日期</label>
            <div class="col-sm-2">
              <input type="text" class="form-control" id="patient_date"  readonly='true' value="{{patient.ptime}}">
            </div>
          </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-default" style="margin-left:20px"> <a href="{% url 'school_1:edit_patient' patient.id %}" style="text-decoration: none;color:#000000;">修改</a></button>
                   
                  </div>
                </div>

              </form>

          </div>
          
        </div>


    </div>
</div>
</body>
</html>